name: cashflow

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      cashflow:
        ipv4_address: 10.7.0.5
    depends_on:
      - ui
      - api
  ui:
    build:
      context: ./ui
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app/ui
    networks:
      - cashflow
    depends_on:
      - api
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api/src:/app/api/src
      - ./api/package.json:/app/api/package.json
      - ./api/tsconfig.json:/app/api/tsconfig.json
    networks:
      - cashflow
    environment:
      ORIGIN_URL: ${ORIGIN_URL}
      ORIGIN_DOMAIN: ${ORIGIN_DOMAIN}
      APP_PORT: ${APP_PORT}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
      GOOGLE_OAUTH_CALLBACK: ${GOOGLE_OAUTH_CALLBACK}
      GOOGLE_OAUTH_SCOPE_USER_INFO: ${GOOGLE_OAUTH_SCOPE_USER_INFO}
      GOOGLE_OAUTH_SCOPE_EMAIL: ${GOOGLE_OAUTH_SCOPE_EMAIL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cashflow
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

networks:
  cashflow:
    attachable: false
    ipam:
      config:
        - subnet: 10.7.0.0/28
volumes:
  postgres_data:

