networks:
  cashflow:
    external: true
services:
  nginx:
      build:
        context: .
      ports:
        - "80:80"
        - "443:443"  # Expose HTTPS port
      networks:
        cashflow:
          ipv4_address: 10.7.0.5