networks:
  cashflow:
    external: true

services:
  ui:
    container_name: cashflow-ui
    build:
      context: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development 
    networks:
      cashflow:
        ipv4_address: 10.7.0.7
